development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE']%>
  domain: <%= ENV['DOMAIN']%>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE']%>
  domain: <%= ENV['DOMAIN']%>

stage:
  secret_key_base: <%= ENV['SECRET_KEY_BASE']%>
  domain: <%= ENV['DOMAIN']%>